var teamComps = [
  {
    unit1: ["mitsuki", 5],
    unit2: ["djeeta", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 3],
    damage: 1286575,
    boss: 2,
    lap: 1,
    clanBattle: 6,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["saren", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1274444,
    boss: 2,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 3],
    unit3: ["misato", 5],
    unit4: ["akari", 4],
    unit5: ["ilya", 5],
    damage: 1046744,
    boss: 3,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 989411,
    boss: 3,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1343753,
    boss: 4,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["yukari", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1206839,
    boss: 4,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["djeeta", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1291084,
    boss: 4,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["saren", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1345229,
    boss: 5,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["misato", 2],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1046744,
    boss: 3,
    clanBattle: 6,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1008419,
    boss: 1,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1144933,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1381250,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "FennekZero",
    notes:
      "MANUAL: Tank swap with Kokkoro and align Kaori + Hiyori UB with Makoto UB"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1337653,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1264448,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 4],
    unit5: ["jun", 3],
    damage: 1157580,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["hatsune", 5],
    unit4: ["karyl", 5],
    unit5: ["akari", 5],
    damage: 956436,
    boss: 3,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Akari dies but it's alright (sort of)"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1085609,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "Shrek",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["misato", 2],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1052855,
    boss: 3,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["yukari", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 863869,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "FennekZero",
    notes: "MANUAL: Line up UBs with Mitsuki's circle"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["yukari", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 797244,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["yukari", 5],
    unit4: ["eriko", 4],
    unit5: ["makoto", 5],
    damage: 750948,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["yukari", 5],
    unit3: ["eriko", 4],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 785801,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["yukari", 5],
    unit3: ["eriko", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 869595,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["yukari", 5],
    unit3: ["eriko", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 585940,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["eriko", 4],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 579404,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 3],
    unit3: ["s kokkoro", 3],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 642313,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 3],
    unit3: ["yukari", 3],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 755732,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 3],
    unit3: ["mitsuki", 5],
    unit4: ["yukari", 5],
    unit5: ["makoto", 5],
    damage: 640837,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["mimi", 5],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 616074,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 5],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 608029,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["tamaki", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 756592,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 884140,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "wasd3223",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["s kokkoro", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1177493,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "wasd3223",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 3],
    damage: 719602,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["mitsuki", 5],
    unit4: ["yukari", 5],
    unit5: ["makoto", 5],
    damage: 788765,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 986036,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "wasd3223",
    notes: "MOSTLY AUTO: Spam Kaori UB at the last few seconds"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["akari", 5],
    unit4: ["yukari", 3],
    unit5: ["ilya", 5],
    damage: 689147,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "mooTheCow",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 935488,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 4],
    unit2: ["s kokkoro", 5],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 918947,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "Hayabusa",
    notes: "MANUAL"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 909559,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "Shrek",
    notes: "MANUAL"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 4],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 739377,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["mitsuki", 5],
    unit3: ["s kokkoro", 3],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 681820,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 4],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["yukari", 5],
    damage: 683492,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "Bloo",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 5],
    unit2: ["mitsuki", 4],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1489349,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "MANUAL"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["eriko", 4],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1220368,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 3],
    unit2: ["mimi", 3],
    unit3: ["djeeta", 3],
    unit4: ["makoto", 5],
    unit5: ["jun", 3],
    damage: 1000486,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["djeeta", 3],
    unit3: ["eriko", 4],
    unit4: ["makoto", 5],
    unit5: ["jun", 3],
    damage: 946799,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["tamaki", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1203522,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 5],
    unit3: ["s kokkoro", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1158934,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["djeeta", 3],
    unit4: ["eriko", 4],
    unit5: ["makoto", 5],
    damage: 1011573,
    boss: 1,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 996168,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1173585,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - borrowed Asose's or Fennek's Ilya. If Ilya dies, reset your game and try the run again but borrow kyarunyan's Ilya instead for improved survivability."
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1134853,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - borrowed kyarunyan's Ilya for improved survivability but slightly lower damage."
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["hatsune", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1074506,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "Layth",
    notes: "FULL AUTO - for people who don't have Karyl built."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 4],
    damage: 1131149,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s tamaki", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1312512,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - Try to not use this team if possible--we want to save physical teams for other bosses so that people who are missing a lot of units can use mages to hit this boss."
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["s tamaki", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1269838,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["tamaki", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1222024,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["saren", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 4],
    damage: 833646,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Don't use this it's bad."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1162157,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1181418,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1100264,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 4],
    damage: 934151,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Don't use this team; replace Suzuna with Shiori."
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 5],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 5],
    unit5: ["lima", 5],
    damage: 785306,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto dies way too early."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["monika", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1117238,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["yukari", 5],
    unit3: ["eriko", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1022280,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 908102,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["s tamaki", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 939761,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["kokkoro", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 886261,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["tomo", 4],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1212475,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Misery",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s tamaki", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 968162,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1141441,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["djeeta", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1072472,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "SEIMODO",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 941009,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["tamaki", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 978634,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["tomo", 4],
    unit3: ["ayane", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1253103,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Misery",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1072352,
    boss: 6,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["mitsuki", 5],
    unit4: ["makoto", 5],
    unit5: ["lima", 5],
    damage: 912660,
    boss: 6,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "Mostly auto - auto until Suzuna is about to get UB, turn off auto until Mitsuki's def down debuff activates, then turn on auto again."
  },
  {
    unit1: ["hiyori", 5],
    unit2: ["makoto", 5],
    unit3: ["nozomi", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 4],
    damage: 988363,
    boss: 6,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - recommended to NOT use because 1) sometimes all your units die and you lose 200k+ damage, and 2) using Jun + Kaori + Makoto can make it harder to make teams for other bosses. If this team is your last hit for the day then it's alright."
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1125080,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["mitsuki", 5],
    unit4: ["makoto", 5],
    unit5: ["lima", 5],
    damage: 968237,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 3],
    unit3: ["s kokkoro", 3],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 956521,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - good choice for a team 3 after using your main DPS on Bosses 3-5."
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 3],
    unit3: ["s kokkoro", 3],
    unit4: ["djeeta", 4],
    unit5: ["makoto", 5],
    damage: 930886,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - good choice for a team 3 after using your main DPS on Bosses 3-5."
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["djeeta", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1149258,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["mimi", 5],
    unit3: ["s tamaki", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 997571,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1100000,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace Hiyori with Tomo for 100k+ more damage. This comp also works for enrage.",
    special: 1
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1100000,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 1
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["s tamaki", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1150000,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - spam S Tamaki's UB to get one more off at literally the last second. May need to be 9-5 for her last UB to happen. Can also use a variation of this team for B1.",
    special: 1
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1150000,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO - only use this team if you can't build the first three",
    special: 1
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["monika", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1100000,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 2
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["s tamaki", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1250000,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace S Tamaki with regular Tamaki 5* for slightly less damage",
    special: 2
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["djeeta", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1100000,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO - can replace Djeeta with another flex DPS",
    special: 2
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1150000,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO - only use this team if you can't build the first three",
    special: 2
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["djeeta", 4],
    unit3: ["s tamaki", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1102909,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - can replace Djeeta with another flex DPS"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1161519,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["monika", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1100000,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 3
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1100000,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace Hiyori with Tomo for 100k+ more damage. If Hiyori dies you might want to reset. Interestingly, the survivability of this comp actually goes up during enrage, although your damage suffers a bit.",
    special: 3
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["djeeta", 4],
    unit3: ["s tamaki", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1100000,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace Djeeta with another flex DPS, and S Tamaki can be replaced with regular Tamaki.",
    special: 3
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1150000,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 3
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1150000,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO - only use this team if you can't build the first ones",
    special: 3
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["s tamaki", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1102236,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["karyl", 4],
    unit4: ["akari", 5],
    unit5: ["lima", 5],
    damage: 906631,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "realda",
    notes:
      "MOSTLY AUTO - align UBs with debuffs at around 0:45 before turning auto back on for the rest of the fight. Works for enrage as well(?)"
  },
  {
    unit1: ["tamaki", 5],
    unit2: ["makoto", 5],
    unit3: ["nozomi", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 4],
    damage: 1068993,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Taishi",
    notes: "FULL AUTO - for enrage. Nozomi is 10-5."
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["akari", 5],
    unit4: ["ilya", 5],
    unit5: ["kuuka", 5],
    damage: 1004925,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    player: "FennekZero",
    notes: "Can auto, but more consistent with manual"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["akari", 5],
    unit4: ["ilya", 5],
    unit5: ["yukari", 5],
    damage: 1054941,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    player: "Keeluah",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1005027,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["tomo", 4],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["kuuka", 5],
    damage: 1005442,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 4],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1400000,
    boss: 3,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes:
      "ALMOST FULL AUTO - just spam Ilya UB the whole time. She may die in the last 5s but that's okay. You can also manually time Kyouka and S Karyl UBs with Akari and Misato UBs for 100k+ more damage"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 4],
    unit3: ["akari", 5],
    unit4: ["ilya", 5],
    unit5: ["yukari", 5],
    damage: 1000000,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes:
      "FULL AUTO - Ilya has a high chance of dying, but you can spam UB to try to mitigate the risk. If you are afraid of the RNG, you can replace Ilya with regular Karyl for a safer run that does ~125k less damage (although there is still a chance that this comp fails as well)."
  },
  {
    unit1: ["Shiori", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 980000,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes: "FULL AUTO - Can replace Shiori with Hiyori, Arisa, or Tomo"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1300000,
    boss: 2,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["kuuka", 5],
    damage: 1000000,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes: "FULL AUTO - requires 9-6 Hiyori. Can also replace Hiyori with Tomo"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["eriko", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1300000,
    boss: 1,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes:
      "FULL AUTO - you can time the last Eriko UB (she gets it in the last 15s or so) with Makoto UB for more damage. Can also use this team on B2 for ~1.2m damage"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1050000,
    boss: 4,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 621042,
    boss: 4,
    clanBattle: 9,
    lap: 3,
    player: "paoh",
    notes:
      "FULL AUTO - can replace Eriko with Hiyori, Tomo, Djeeta, etc. Can also replace Eriko with S Tamaki if you have her raised for a more consistent 650k+ damage but it requires manual use"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 700000,
    boss: 1,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "MANUAL TANK SWAP - RNG heavily affects damage on this comp. If Kaori dies before you can tank swap, your damage will be closer to 700k. If Kaori lives and you fully manual, you can hit 900k+. This is not the most damaging comp you can use for B1, but it is optimal when you factor in all three of your hits for the day (because this comp only uses 2 defense down debuffers, and you want to save mages for B3/B5 if possible)"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 700000,
    boss: 2,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "MOSTLY AUTO - I had to spam S Tamaki UB to line up with Mitsuki defense shred, but this may change depending on how geared your S Tamaki is."
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 4],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 700000,
    boss: 3,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "EASY MANUAL - Line up UBs with Akari's magic attack buff UB. Spam Ilya UB as necessary to prevent her from dying"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 600000,
    boss: 4,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace Eriko with another flex DPS. Using S Tamaki in place of Eriko and manually playing can get you a consistent 650k+. However, you may want to use Eriko or another flex DPS here instead because this will allow you to hit B2 with the Jun + double Tamaki comp. You should always start your first physical team hit of the day by borrowing Makoto; this way you have the option to make either two Jun comps or two comps with Kaori + Makoto"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 4],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["ilya", 5],
    damage: 1200000,
    boss: 5,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "EASY MANUAL - Line up UBs with Akari's magic attack buff UB. Spam Ilya UB as necessary to prevent her from dying"
  }
];
