var teamComps = [
  {
    unit1: ["mitsuki", 5],
    unit2: ["djeeta", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 3],
    damage: 1286575,
    boss: 2,
    lap: 1,
    clanBattle: 6,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["saren", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1274444,
    boss: 2,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 3],
    unit3: ["misato", 5],
    unit4: ["akari", 4],
    unit5: ["illya", 5],
    damage: 1046744,
    boss: 3,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 989411,
    boss: 3,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1343753,
    boss: 4,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["yukari", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1206839,
    boss: 4,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["djeeta", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1291084,
    boss: 4,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["saren", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1345229,
    boss: 5,
    clanBattle: 6,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["misato", 2],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1046744,
    boss: 3,
    clanBattle: 6,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1008419,
    boss: 1,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1144933,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1381250,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "FennekZero",
    notes:
      "MANUAL: Tank swap with Kokkoro and align Kaori + Hiyori UB with Makoto UB"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1337653,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1264448,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 4],
    unit5: ["jun", 3],
    damage: 1157580,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["hatsune", 5],
    unit4: ["karyl", 5],
    unit5: ["akari", 5],
    damage: 956436,
    boss: 3,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Akari dies but it's alright (sort of)"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1085609,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "Shrek",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["misato", 2],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1052855,
    boss: 3,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["yukari", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 863869,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "FennekZero",
    notes: "MANUAL: Line up UBs with Mitsuki's circle"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["yukari", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 797244,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["yukari", 5],
    unit4: ["eriko", 4],
    unit5: ["makoto", 5],
    damage: 750948,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["yukari", 5],
    unit3: ["eriko", 4],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 785801,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["yukari", 5],
    unit3: ["eriko", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 869595,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["yukari", 5],
    unit3: ["eriko", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 585940,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["eriko", 4],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 579404,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 3],
    unit3: ["s kokkoro", 3],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 642313,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 3],
    unit3: ["yukari", 3],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 755732,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 3],
    unit3: ["mitsuki", 5],
    unit4: ["yukari", 5],
    unit5: ["makoto", 5],
    damage: 640837,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["mimi", 5],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 616074,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 5],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 608029,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["tamaki", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 756592,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 884140,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "wasd3223",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["s kokkoro", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1177493,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "wasd3223",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 3],
    damage: 719602,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["mitsuki", 5],
    unit4: ["yukari", 5],
    unit5: ["makoto", 5],
    damage: 788765,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 986036,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "wasd3223",
    notes: "MOSTLY AUTO: Spam Kaori UB at the last few seconds"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["akari", 5],
    unit4: ["yukari", 3],
    unit5: ["illya", 5],
    damage: 689147,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "mooTheCow",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 935488,
    boss: 4,
    clanBattle: 6,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 4],
    unit2: ["s kokkoro", 5],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 918947,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "Hayabusa",
    notes: "MANUAL"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 909559,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "Shrek",
    notes: "MANUAL"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 4],
    unit4: ["kaori", 5],
    unit5: ["jun", 3],
    damage: 739377,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["mitsuki", 5],
    unit3: ["s kokkoro", 3],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 681820,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 4],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["yukari", 5],
    damage: 683492,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "Bloo",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 5],
    unit2: ["mitsuki", 4],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1489349,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "MANUAL"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["eriko", 4],
    unit4: ["makoto", 4],
    unit5: ["kaori", 5],
    damage: 1220368,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 3],
    unit2: ["mimi", 3],
    unit3: ["djeeta", 3],
    unit4: ["makoto", 5],
    unit5: ["jun", 3],
    damage: 1000486,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["djeeta", 3],
    unit3: ["eriko", 4],
    unit4: ["makoto", 5],
    unit5: ["jun", 3],
    damage: 946799,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["tamaki", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1203522,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 5],
    unit3: ["s kokkoro", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1158934,
    boss: 2,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["s kokkoro", 3],
    unit3: ["djeeta", 3],
    unit4: ["eriko", 4],
    unit5: ["makoto", 5],
    damage: 1011573,
    boss: 1,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 996168,
    boss: 5,
    clanBattle: 6,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1173585,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - borrowed Asose's or Fennek's illya. If illya dies, reset your game and try the run again but borrow kyarunyan's illya instead for improved survivability."
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1134853,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - borrowed kyarunyan's illya for improved survivability but slightly lower damage."
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["hatsune", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1074506,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "Layth",
    notes: "FULL AUTO - for people who don't have Karyl built."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 4],
    damage: 1131149,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s tamaki", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1312512,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - Try to not use this team if possible--we want to save physical teams for other bosses so that people who are missing a lot of units can use mages to hit this boss."
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["s tamaki", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1269838,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["tamaki", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1222024,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["saren", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 4],
    damage: 833646,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Don't use this it's bad."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["mitsuki", 5],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1162157,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1181418,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1100264,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 4],
    damage: 934151,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Don't use this team; replace Suzuna with Shiori."
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 5],
    unit3: ["kokkoro", 5],
    unit4: ["makoto", 5],
    unit5: ["lima", 5],
    damage: 785306,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto dies way too early."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["monika", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1117238,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["yukari", 5],
    unit3: ["eriko", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1022280,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 908102,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["s tamaki", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 939761,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 3],
    unit2: ["kokkoro", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 886261,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["tomo", 4],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1212475,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Misery",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s tamaki", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 968162,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1141441,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["djeeta", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1072472,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "SEIMODO",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 941009,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["tamaki", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 978634,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["tomo", 4],
    unit3: ["ayane", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1253103,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Misery",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1072352,
    boss: 6,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["mitsuki", 5],
    unit4: ["makoto", 5],
    unit5: ["lima", 5],
    damage: 912660,
    boss: 6,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "Mostly auto - auto until Suzuna is about to get UB, turn off auto until Mitsuki's def down debuff activates, then turn on auto again."
  },
  {
    unit1: ["hiyori", 5],
    unit2: ["makoto", 5],
    unit3: ["nozomi", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 4],
    damage: 988363,
    boss: 6,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - recommended to NOT use because 1) sometimes all your units die and you lose 200k+ damage, and 2) using Jun + Kaori + Makoto can make it harder to make teams for other bosses. If this team is your last hit for the day then it's alright."
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1125080,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["mitsuki", 5],
    unit4: ["makoto", 5],
    unit5: ["lima", 5],
    damage: 968237,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 3],
    unit3: ["s kokkoro", 3],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 956521,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - good choice for a team 3 after using your main DPS on Bosses 3-5."
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["arisa", 3],
    unit3: ["s kokkoro", 3],
    unit4: ["djeeta", 4],
    unit5: ["makoto", 5],
    damage: 930886,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - good choice for a team 3 after using your main DPS on Bosses 3-5."
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["djeeta", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1149258,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["mimi", 5],
    unit3: ["s tamaki", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 997571,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1100000,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace Hiyori with Tomo for 100k+ more damage. This comp also works for enrage.",
    special: 1
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1100000,
    boss: 3,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 1
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["s tamaki", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1150000,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - spam S Tamaki's UB to get one more off at literally the last second. May need to be 9-5 for her last UB to happen. Can also use a variation of this team for B1.",
    special: 1
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1150000,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO - only use this team if you can't build the first three",
    special: 1
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["monika", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1100000,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 2
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["s tamaki", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1250000,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace S Tamaki with regular Tamaki 5* for slightly less damage",
    special: 2
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["djeeta", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1100000,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO - can replace Djeeta with another flex DPS",
    special: 2
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1150000,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO - only use this team if you can't build the first three",
    special: 2
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["djeeta", 4],
    unit3: ["s tamaki", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1102909,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - can replace Djeeta with another flex DPS"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1161519,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["suzuna", 5],
    unit3: ["monika", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1100000,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 3
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["lima", 5],
    damage: 1100000,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace Hiyori with Tomo for 100k+ more damage. If Hiyori dies you might want to reset. Interestingly, the survivability of this comp actually goes up during enrage, although your damage suffers a bit.",
    special: 3
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["djeeta", 4],
    unit3: ["s tamaki", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1100000,
    boss: 1,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace Djeeta with another flex DPS, and S Tamaki can be replaced with regular Tamaki.",
    special: 3
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1150000,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 3
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1150000,
    boss: 2,
    clanBattle: 7,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO - only use this team if you can't build the first ones",
    special: 3
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["s tamaki", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1102236,
    boss: 4,
    clanBattle: 7,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["karyl", 4],
    unit4: ["akari", 5],
    unit5: ["lima", 5],
    damage: 906631,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "realda",
    notes:
      "MOSTLY AUTO - align UBs with debuffs at around 0:45 before turning auto back on for the rest of the fight. Works for enrage as well(?)"
  },
  {
    unit1: ["tamaki", 5],
    unit2: ["makoto", 5],
    unit3: ["nozomi", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 4],
    damage: 1068993,
    boss: 5,
    clanBattle: 7,
    lap: 2,
    player: "Taishi",
    notes: "FULL AUTO - for enrage. Nozomi is 10-5."
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 3],
    unit3: ["akari", 5],
    unit4: ["illya", 5],
    unit5: ["kuuka", 5],
    damage: 1004925,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    player: "FennekZero",
    notes: "Can auto, but more consistent with manual"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["akari", 5],
    unit4: ["illya", 5],
    unit5: ["yukari", 5],
    damage: 1054941,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    player: "Keeluah",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1005027,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["tomo", 4],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["kuuka", 5],
    damage: 1005442,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 4],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1400000,
    boss: 3,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes:
      "ALMOST FULL AUTO - just spam illya UB the whole time. She may die in the last 5s but that's okay. You can also manually time Kyouka and S Karyl UBs with Akari and Misato UBs for 100k+ more damage"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 4],
    unit3: ["akari", 5],
    unit4: ["illya", 5],
    unit5: ["yukari", 5],
    damage: 1000000,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes:
      "FULL AUTO - illya has a high chance of dying, but you can spam UB to try to mitigate the risk. If you are afraid of the RNG, you can replace illya with regular Karyl for a safer run that does ~125k less damage (although there is still a chance that this comp fails as well)."
  },
  {
    unit1: ["Shiori", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 980000,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes: "FULL AUTO - Can replace Shiori with Hiyori, Arisa, or Tomo"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1300000,
    boss: 2,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["kuuka", 5],
    damage: 1000000,
    boss: 5,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes: "FULL AUTO - requires 9-6 Hiyori. Can also replace Hiyori with Tomo"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["eriko", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1300000,
    boss: 1,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes:
      "FULL AUTO - you can time the last Eriko UB (she gets it in the last 15s or so) with Makoto UB for more damage. Can also use this team on B2 for ~1.2m damage"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1050000,
    boss: 4,
    clanBattle: 9,
    lap: 2,
    special: 1,
    player: "Symphonia",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 621042,
    boss: 4,
    clanBattle: 9,
    lap: 3,
    player: "paoh",
    notes:
      "FULL AUTO - can replace Eriko with Hiyori, Tomo, Djeeta, etc. Can also replace Eriko with S Tamaki if you have her raised for a more consistent 650k+ damage but it requires manual use"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["kokkoro", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 700000,
    boss: 1,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "MANUAL TANK SWAP - RNG heavily affects damage on this comp. If Kaori dies before you can tank swap, your damage will be closer to 700k. If Kaori lives and you fully manual, you can hit 900k+. This is not the most damaging comp you can use for B1, but it is optimal when you factor in all three of your hits for the day (because this comp only uses 2 defense down debuffers, and you want to save mages for B3/B5 if possible)"
  },
  {
    unit1: ["mitsuki", 5],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 700000,
    boss: 2,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "MOSTLY AUTO - I had to spam S Tamaki UB to line up with Mitsuki defense shred, but this may change depending on how geared your S Tamaki is. H Miyako is actually great here (can replace S Tamaki with H Miyako) if you have her built."
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 4],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 700000,
    boss: 3,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "EASY MANUAL - Line up UBs with Akari's magic attack buff UB. Spam illya UB as necessary to prevent her from dying"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 600000,
    boss: 4,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace Eriko with another flex DPS. Using S Tamaki in place of Eriko and manually playing can get you a consistent 650k+. However, you may want to use Eriko or another flex DPS here instead because this will allow you to hit B2 with the Jun + double Tamaki comp (assuming you don't have H Miyako). You should always start your first physical team hit of the day by borrowing Makoto; this way you have the option to make either two Jun comps or two comps with Kaori + Makoto"
  },
  {
    unit1: ["kyouka", 3],
    unit2: ["s karyl", 4],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1200000,
    boss: 5,
    clanBattle: 9,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes:
      "EASY MANUAL - Line up UBs with Akari's magic attack buff UB. Spam illya UB as necessary to prevent her from dying"
  },
  {
    unit1: ["shinobu", 3],
    unit2: ["christina", 5],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1584833,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes:
      "FULL AUTO - tested with R9 Makoto. Using R11 Makoto can do an extra 100k damage"
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1452578,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes:
      "FULL AUTO - tested with R9 Makoto. Using R11 Makoto can do an extra 100k damage"
  },
  {
    unit1: ["christina", 5],
    unit2: ["tomo", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1335348,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes:
      "FULL AUTO - tested with R9 Makoto. Using R11 Makoto can do an extra 100k damage"
  },
  {
    unit1: ["christina", 5],
    unit2: ["eriko", 5],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1336976,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes:
      "FULL AUTO - tested with R9 Makoto. Using R11 Makoto can do an extra 100k damage"
  },
  {
    unit1: ["christina", 5],
    unit2: ["eriko", 5],
    unit3: ["hiyori", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1286322,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes:
      "FULL AUTO - tested with R9 Makoto. Using R11 Makoto can do an extra 100k damage"
  },
  {
    unit1: ["shinobu", 3],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1519157,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shinobu", 3],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1468819,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R9 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1899673,
    boss: 1,
    clanBattle: 10,
    lap: 1,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 3],
    unit5: ["kaori", 5],
    damage: 1560335,
    boss: 2,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R9 Makoto"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 3],
    unit5: ["kaori", 5],
    damage: 1410396,
    boss: 4,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R9 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1941962,
    boss: 4,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R9 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1366277,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R9 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 2089040,
    boss: 1,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1880316,
    boss: 1,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1963318,
    boss: 2,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1738181,
    boss: 4,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1282064,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["mimi", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 1945045,
    boss: 1,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["mimi", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 1993393,
    boss: 2,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["mimi", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 1728537,
    boss: 4,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["mimi", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 1337805,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["kokkoro", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1677393,
    boss: 1,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["kokkoro", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1895290,
    boss: 2,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["kokkoro", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1640285,
    boss: 4,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["kokkoro", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1229579,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1997018,
    boss: 2,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1850228,
    boss: 4,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1192363,
    boss: 5,
    clanBattle: 10,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["h misaki", 3],
    unit2: ["kyouka", 4],
    unit3: ["s karyl", 5],
    unit4: ["karyl", 5],
    unit5: ["illya", 5],
    damage: 1696706,
    boss: 3,
    clanBattle: 10,
    lap: 1,
    player: "FennekZero",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["nanaka", 4],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1710111,
    boss: 3,
    clanBattle: 10,
    lap: 1,
    player: "Blacklotus",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 5],
    unit3: ["eriko", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 608561,
    boss: 5,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shinobu", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1099023,
    boss: 5,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["christina", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 1835398,
    boss: 1,
    clanBattle: 10,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["christina", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1796629,
    boss: 1,
    clanBattle: 10,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1780347,
    boss: 2,
    clanBattle: 10,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1688046,
    boss: 2,
    clanBattle: 10,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - R11 Makoto"
  },
  {
    unit1: ["christina", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1348441,
    boss: 5,
    clanBattle: 10,
    lap: 2,
    player: "realda",
    notes: "SEMI AUTO - R11 Makoto; line up UBs with Makoto UB."
  },
  {
    unit1: ["christina", 5],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1364029,
    boss: 5,
    clanBattle: 10,
    lap: 2,
    player: "realda",
    notes: "SEMI AUTO - R11 Makoto; line up UBs with Makoto UB."
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1516709,
    boss: 4,
    clanBattle: 10,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["tomo", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1378487,
    boss: 5,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["ruka", 3],
    damage: 1300541,
    boss: 4,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1516709,
    boss: 4,
    clanBattle: 10,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["s tamaki", 3],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1516709,
    boss: 4,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["arisa", 4],
    unit2: ["mitsuki", 5],
    unit3: ["kokkoro", 3],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 1335051,
    boss: 2,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes: "SEMI-AUTO - basically full auto except tank swap Kokkoro."
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1196206,
    boss: 3,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - illya dies immediately, don't try this without a healer unless you are Hayabusa."
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 3],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1295132,
    boss: 3,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes: "ALMOST FULL AUTO - spam illya UB as necessary to keep her alive."
  },
  {
    unit1: ["christina", 5],
    unit2: ["tomo", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1350000,
    boss: 5,
    clanBattle: 10,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - there are a lot of small optimizations you can do if you line up UBs with Makoto UB to get +150k or more damage. Can replace Tomo with Hiyori or another flex DPS.",
    special: 1
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1400000,
    boss: 4,
    clanBattle: 10,
    lap: 2,
    player: "Symphonia",
    notes:
      "FULL AUTO - can replace S Tamaki with regular Tamaki. Eriko is preferred here; try not to replace her.",
    special: 1
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["christina", 5],
    damage: 1400000,
    boss: 3,
    clanBattle: 10,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO.",
    special: 1
  },
  {
    unit1: ["arisa", 4],
    unit2: ["mitsuki", 5],
    unit3: ["kokkoro", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 1100000,
    boss: 1,
    clanBattle: 10,
    lap: 2,
    player: "Symphonia",
    notes:
      "SEMI-AUTO - basically full auto, except manual to tank swap Kokkoro in. This comp does ~1.1m on B1 or ~1.3m on B2. Sub out Arisa or Djeeta as necessary with other flex DPS (that you aren't already using on Boss 4 or 5).",
    special: 1
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 3],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["christina", 5],
    damage: 1405638,
    boss: 3,
    clanBattle: 10,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["h misaki", 3],
    unit2: ["kyouka", 4],
    unit3: ["s karyl", 3],
    unit4: ["nanaka", 4],
    unit5: ["illya", 5],
    damage: 1785636,
    boss: 3,
    clanBattle: 10,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["mitsuki", 5],
    unit3: ["christina", 5],
    unit4: ["tamaki", 5],
    unit5: ["tamaki", 5],
    damage: 1503946,
    boss: 5,
    clanBattle: 11,
    lap: 1,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["rei", 4],
    unit2: ["eriko", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1697687,
    boss: 5,
    clanBattle: 11,
    lap: 1,
    player: "realda",
    notes: "Hiyori and Rei have UE"
  },
  {
    unit1: ["rei", 4],
    unit2: ["djeeta", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1847925,
    boss: 5,
    clanBattle: 11,
    lap: 1,
    player: "realda",
    notes: "Hiyori and Rei have UE"
  },
  {
    unit1: ["christina", 5],
    unit2: ["rei", 4],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2068320,
    boss: 5,
    clanBattle: 11,
    lap: 1,
    player: "realda",
    notes: "Hiyori and Rei have UE"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 3],
    unit3: ["nanaka", 3],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1300184,
    boss: 5,
    clanBattle: 11,
    lap: 1,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 2012913,
    boss: 1,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes:
      "FULL AUTO - Makoto 9-6, Shiori 11-5, everyone else 11-6 (except Saren but she doesn't matter)"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 2022223,
    boss: 2,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes:
      "FULL AUTO - Makoto 9-6, Shiori 11-5, everyone else 11-6 (except Saren but she doesn't matter)"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["rei", 4],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1183469,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["rei", 4],
    unit3: ["tomo", 3],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1028237,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["rei", 4],
    unit3: ["tomo", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1249574,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["rei", 4],
    unit2: ["tomo", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1334834,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["rei", 4],
    unit2: ["s tamaki", 3],
    unit3: ["tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1343594,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["rei", 4],
    unit3: ["tomo", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 896736,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["rei", 4],
    unit3: ["eriko", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1087416,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["mimi", 5],
    unit2: ["rei", 4],
    unit3: ["djeeta", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 1227816,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 4],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1499030,
    boss: 4,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 4],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1657744,
    boss: 4,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["rei", 4],
    unit2: ["tomo", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1934790,
    boss: 5,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1855076,
    boss: 1,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1894527,
    boss: 2,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1323609,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1719709,
    boss: 5,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mimi", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 4],
    unit4: ["djeeta", 5],
    unit5: ["tamaki", 5],
    damage: 1462359,
    boss: 1,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mimi", 5],
    unit2: ["rei", 4],
    unit3: ["djeeta", 5],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1675640,
    boss: 1,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["mimi", 5],
    unit2: ["rei", 4],
    unit3: ["djeeta", 5],
    unit4: ["tamaki", 5],
    unit5: ["makoto", 5],
    damage: 1548529,
    boss: 2,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["kokkoro", 5],
    unit3: ["rei", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1755422,
    boss: 1,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["kokkoro", 5],
    unit3: ["rei", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1919473,
    boss: 2,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["kokkoro", 5],
    unit3: ["rei", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1463082,
    boss: 3,
    clanBattle: 11,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["rei", 4],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1537387,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["rei", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1555319,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["rei", 4],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1537387,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - Hiyori UE"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["c ayane", 5],
    unit5: ["makoto", 5],
    damage: 2055297,
    boss: 2,
    clanBattle: 11,
    lap: 2,
    player: "Toon",
    notes:
      "SOME AUTO - need to watch C Ayane and hold her third UB so she doesn't kill herself"
  },
  {
    unit1: ["arisa", 4],
    unit2: ["s kokkoro", 3],
    unit3: ["christina", 5],
    unit4: ["c ayane", 5],
    unit5: ["makoto", 5],
    damage: 1874095,
    boss: 2,
    clanBattle: 11,
    lap: 2,
    player: "Toon",
    notes:
      "SOME AUTO - need to watch C Ayane and hold her third UB so she doesn't kill herself"
  },
  {
    unit1: ["arisa", 4],
    unit2: ["s kokkoro", 3],
    unit3: ["christina", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 1867127,
    boss: 2,
    clanBattle: 11,
    lap: 2,
    player: "Toon",
    notes: "AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["christina", 5],
    unit3: ["s tamaki", 3],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 1238372,
    boss: 3,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["rei", 4],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1305461,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["shizuru", 5],
    unit2: ["rei", 4],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1017007,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["rei", 4],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["ruka", 3],
    unit5: ["kaori", 5],
    damage: 1117257,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["rei", 4],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1246899,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["tomo", 3],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1763776,
    boss: 1,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["tomo", 3],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1922546,
    boss: 1,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto cannot be 9-6 or she dies"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["s tamaki", 3],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1990052,
    boss: 1,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto not 9-6"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["karyl", 5],
    unit4: ["akari", 5],
    unit5: ["yukari", 5],
    damage: 1142492,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Karyl doesn't have UE"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["nanaka", 5],
    unit4: ["akari", 5],
    unit5: ["yukari", 5],
    damage: 1205519,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1254438,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["s tamaki", 3],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1850046,
    boss: 2,
    clanBattle: 11,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["rei", 4],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1500000,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 1
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["misato", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1250000,
    boss: 5,
    clanBattle: 11,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 1
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["s tamaki", 3],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1900000,
    boss: 1,
    clanBattle: 11,
    lap: 2,
    player: "Symphonia",
    notes: "FULL AUTO",
    special: 1
  },
  {
    unit1: ["arisa", 4],
    unit2: ["christina", 5],
    unit3: ["rei", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1766570,
    boss: 3,
    clanBattle: 11,
    lap: 2,
    player: "Bshandon",
    notes: "SEMI AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["saren", 5],
    unit3: ["christina", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 1732251,
    boss: 3,
    clanBattle: 11,
    lap: 2,
    player: "Bshandon",
    notes: "SEMI AUTO"
  },
  {
    unit1: ["kasumi", 5],
    unit2: ["kasumi", 5],
    unit3: ["kasumi", 5],
    unit4: ["kasumi", 5],
    unit5: ["kasumi", 5],
    damage: 99999999,
    boss: 1,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes:
      "This comp is just a placeholder. Check back for updates soon<sup>TM</sup>."
  },
  {
    unit1: ["christina", 5],
    unit2: ["rei", 5],
    unit3: ["makoto", 5],
    unit4: ["hiyori", 5],
    unit5: ["kaori", 5],
    damage: 2341396,
    boss: 2,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6, Rei has UE."
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 2104206,
    boss: 2,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["tomo", 3],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1998277,
    boss: 2,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["christina", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 2100000,
    boss: 2,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["christina", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["ny rei", 3],
    unit5: ["kaori", 5],
    damage: 1974038,
    boss: 3,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["djeeta", 5],
    unit5: ["ny rei", 3],
    damage: 2070592,
    boss: 3,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["ruka", 3],
    unit5: ["kaori", 5],
    damage: 1903051,
    boss: 3,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["christina", 5],
    unit2: ["rei", 5],
    unit3: ["eriko", 5],
    unit4: ["hiyori", 5],
    unit5: ["ny rei", 3],
    damage: 1732586,
    boss: 3,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["saren", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2139779,
    boss: 3,
    clanBattle: 12,
    lap: 1,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["yukari", 5],
    unit2: ["christina", 5],
    unit3: ["s tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2345961,
    boss: 3,
    clanBattle: 12,
    lap: 1,
    player: "Jari",
    notes: "FULL AUTO"
  },
  {
    unit1: ["rei", 5],
    unit2: ["hiyori", 5],
    unit3: ["makoto", 5],
    unit4: ["ny rei", 5],
    unit5: ["kaori", 5],
    damage: 2087125,
    boss: 3,
    clanBattle: 12,
    lap: 1,
    player: "Toon",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["christina", 5],
    unit2: ["rei", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["ny rei", 5],
    damage: 2051313,
    boss: 3,
    clanBattle: 12,
    lap: 1,
    player: "Toon",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2269283,
    boss: 4,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["christina", 5],
    unit2: ["tomo", 3],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2157113,
    boss: 4,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 5],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2348430,
    boss: 4,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["ny hiyori", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2279302,
    boss: 4,
    clanBattle: 12,
    lap: 1,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["arisa", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2289565,
    boss: 5,
    clanBattle: 12,
    lap: 1,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 4],
    unit3: ["nanaka", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 1989716,
    boss: 5,
    clanBattle: 12,
    lap: 1,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["tomo", 4],
    unit3: ["ny hiyori", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2286229,
    boss: 5,
    clanBattle: 12,
    lap: 1,
    player: "Toon",
    notes:
      "MOSTLY AUTO - spam Kaori UB at 20s so she gets another UB at the end."
  },
  {
    unit1: ["saren", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 2178284,
    boss: 5,
    clanBattle: 12,
    lap: 1,
    player: "Toon",
    notes: "FULL AUTO"
  },
  {
    unit1: ["saren", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 1881408,
    boss: 5,
    clanBattle: 12,
    lap: 1,
    player: "Toon",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["eriko", 5],
    unit5: ["makoto", 5],
    damage: 2084729,
    boss: 5,
    clanBattle: 12,
    lap: 1,
    player: "FennekZero",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2108578,
    boss: 5,
    clanBattle: 12,
    lap: 1,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["rei", 5],
    unit3: ["s tamaki", 3],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1607701,
    boss: 1,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["arisa", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["rei", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1614469,
    boss: 1,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2076885,
    boss: 1,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2401660,
    boss: 1,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["s tamaki", 3],
    unit5: ["makoto", 5],
    damage: 2190151,
    boss: 2,
    clanBattle: 12,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 2084205,
    boss: 2,
    clanBattle: 12,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["tomo", 4],
    unit3: ["ny hiyori", 4],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2551482,
    boss: 2,
    clanBattle: 12,
    lap: 2,
    player: "Toon",
    notes: "SEMI AUTO"
  },
  {
    unit1: ["yukari", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1827310,
    boss: 3,
    clanBattle: 12,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - Rei and Hiyori both have UE."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["rei", 5],
    unit5: ["makoto", 5],
    damage: 1770108,
    boss: 3,
    clanBattle: 12,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["saren", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1729776,
    boss: 3,
    clanBattle: 12,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2112789,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - Hiyori has UE."
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1805541,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Hiyori does not have UE."
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2078727,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["eriko", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1731024,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["kokkoro", 5],
    unit3: ["christina", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1722900,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["kokkoro", 4],
    unit3: ["christina", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1892088,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "toon",
    notes: "FULL AUTO - Makoto 9-6, Hiyori has UE."
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["kokkoro", 4],
    unit3: ["christina", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1804314,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["christina", 5],
    unit2: ["tomo", 4],
    unit3: ["hiyori", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 1771211,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Makoto 9-6."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["djeeta", 5],
    unit5: ["ny rei", 3],
    damage: 1357841,
    boss: 3,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["saren", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 1887993,
    boss: 3,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s karyl", 4],
    unit2: ["nanaka", 5],
    unit3: ["akari", 5],
    unit4: ["illya", 5],
    unit5: ["shizuru", 5],
    damage: 1585946,
    boss: 5,
    clanBattle: 12,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["karyl", 5],
    unit3: ["akari", 5],
    unit4: ["illya", 5],
    unit5: ["shizuru", 5],
    damage: 1445832,
    boss: 5,
    clanBattle: 12,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["nanaka", 5],
    unit4: ["misato", 5],
    unit5: ["akari", 5],
    damage: 1595412,
    boss: 5,
    clanBattle: 12,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["ny yui", 3],
    unit4: ["nanaka", 3],
    unit5: ["akari", 5],
    damage: 1838244,
    boss: 5,
    clanBattle: 12,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["nanaka", 5],
    unit4: ["misato", 5],
    unit5: ["illya", 5],
    damage: 1750232,
    boss: 5,
    clanBattle: 12,
    lap: 2,
    player: "Toon",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 3],
    unit3: ["misato", 5],
    unit4: ["akari", 4],
    unit5: ["illya", 5],
    damage: 1700000,
    boss: 5,
    clanBattle: 12,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes:
      "MOSTLY AUTO - spam Illya UB the whole time and pray she doesn't die. NY Yui and Nanaka comps are safer, so use those if you have them."
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2300000,
    boss: 1,
    clanBattle: 12,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["tomo", 3],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2000000,
    boss: 4,
    clanBattle: 12,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes: "FULL AUTO"
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 2000000,
    boss: 2,
    clanBattle: 12,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes: "FULL AUTO - Rei has UE"
  },
  {
    unit1: ["saren", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 1800000,
    boss: 3,
    clanBattle: 12,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 3],
    unit3: ["misato", 5],
    unit4: ["akari", 4],
    unit5: ["illya", 5],
    damage: 1702670,
    boss: 5,
    clanBattle: 12,
    lap: 2,
    player: "paoh",
    notes:
      "MOSTLY AUTO - spam Illya UB the whole time and pray she doesn't die."
  },
  {
    unit1: ["christina", 5],
    unit2: ["rei", 5],
    unit3: ["s tamaki", 4],
    unit4: ["makoto", 5],
    unit5: ["jun", 5],
    damage: 1535054,
    boss: 1,
    clanBattle: 12,
    lap: 3,
    player: "Sqorl",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["saren", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["eriko", 5],
    unit5: ["makoto", 5],
    damage: 1306844,
    boss: 3,
    clanBattle: 12,
    lap: 3,
    player: "Fennek",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["ny yui", 3],
    unit4: ["misato", 5],
    unit5: ["akari", 5],
    damage: 1334469,
    boss: 5,
    clanBattle: 12,
    lap: 3,
    player: "Toon",
    notes: "FULL AUTO"
  },
  {
    unit1: ["saren", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["rei", 5],
    unit5: ["makoto", 5],
    damage: 1375475,
    boss: 3,
    clanBattle: 12,
    lap: 3,
    player: "realda",
    notes: "FULL AUTO - Rei has UE."
  },
  {
    unit1: ["saren", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["djeeta", 5],
    unit5: ["makoto", 5],
    damage: 1235304,
    boss: 3,
    clanBattle: 12,
    lap: 3,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1315108,
    boss: 4,
    clanBattle: 12,
    lap: 3,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["ny yui", 3],
    unit4: ["nanaka", 5],
    unit5: ["akari", 5],
    damage: 1621473,
    boss: 5,
    clanBattle: 12,
    lap: 3,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["ny yui", 3],
    unit4: ["nanaka", 5],
    unit5: ["akari", 5],
    damage: 1590835,
    boss: 2,
    clanBattle: 12,
    lap: 3,
    player: "Toon",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["karyl", 5],
    unit4: ["ny yui", 3],
    unit5: ["nanaka", 5],
    damage: 1626288,
    boss: 2,
    clanBattle: 12,
    lap: 3,
    player: "Toon",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1648752,
    boss: 1,
    clanBattle: 12,
    lap: 3,
    player: "realda",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1648752,
    boss: 2,
    clanBattle: 12,
    lap: 3,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1146963,
    boss: 4,
    clanBattle: 12,
    lap: 3,
    player: "paoh",
    notes: "FULL AUTO"
  },
  {
    unit1: ["suzuna", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["christina", 5],
    unit4: ["rei", 5],
    unit5: ["makoto", 5],
    damage: 0,
    boss: 4,
    clanBattle: 12,
    lap: 3,
    player: "paoh",
    notes: "FULL AUTO - Doesn't work, Christina dies."
  },
  {
    unit1: ["arisa", 5],
    unit2: ["s kokkoro", 3],
    unit3: ["christina", 5],
    unit4: ["rei", 5],
    unit5: ["makoto", 5],
    damage: 0,
    boss: 4,
    clanBattle: 12,
    lap: 3,
    player: "paoh",
    notes: "FULL AUTO - Doesn't work, Christina dies."
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["hiyori", 5],
    unit5: ["makoto", 5],
    damage: 1032572,
    boss: 4,
    clanBattle: 12,
    lap: 3,
    player: "paoh",
    notes: "FULL AUTO - Some units die but it's ok."
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 1742065,
    boss: 2,
    clanBattle: 12,
    lap: 3,
    player: "paoh",
    notes: "FULL AUTO - S Kokkoro dies but it's ok."
  },
  {
    unit1: ["christina", 5],
    unit2: ["s tamaki", 3],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1600000,
    boss: 1,
    clanBattle: 12,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kokkoro", 5],
    unit2: ["christina", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1300000,
    boss: 4,
    clanBattle: 12,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes: "FULL AUTO"
  },
  {
    unit1: ["s kokkoro", 3],
    unit2: ["christina", 5],
    unit3: ["rei", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 1700000,
    boss: 2,
    clanBattle: 12,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes: "FULL AUTO - S Kokkoro dies but it's ok."
  },
  {
    unit1: ["saren", 5],
    unit2: ["yukari", 5],
    unit3: ["christina", 5],
    unit4: ["rei", 5],
    unit5: ["makoto", 5],
    damage: 1300000,
    boss: 3,
    clanBattle: 12,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes: "FULL AUTO"
  },
  {
    unit1: ["kyouka", 4],
    unit2: ["s karyl", 5],
    unit3: ["ny yui", 3],
    unit4: ["nanaka", 5],
    unit5: ["akari", 5],
    damage: 1500000,
    boss: 5,
    clanBattle: 12,
    lap: 3,
    special: 2,
    player: "Symphonia",
    notes: "FULL AUTO"
  },
  {
    unit1: ["christina", 5],
    unit2: ["eriko", 5],
    unit3: ["s tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 3502203,
    boss: 1,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Eriko and Kaori."
  },
  {
    unit1: ["christina", 5],
    unit2: ["eriko", 5],
    unit3: ["s tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 3699962,
    boss: 2,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Eriko and Kaori."
  },
  {
    unit1: ["christina", 5],
    unit2: ["eriko", 5],
    unit3: ["s tamaki", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2537910,
    boss: 3,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes:
      "ALMOST FULL AUTO - Manual on S Tamaki's first UB, then full auto until Makoto and Kaori get their last UBs at around 15s remaining."
  },
  {
    unit1: ["v shizuru", 3],
    unit2: ["rei", 5],
    unit3: ["tomo", 4],
    unit4: ["makoto", 5],
    unit5: ["muimi", 5],
    damage: 2406370,
    boss: 2,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Rei and Makoto."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["eriko", 5],
    unit5: ["makoto", 5],
    damage: 3723273,
    boss: 3,
    clanBattle: 15,
    lap: 2,
    player: "Toon",
    notes: "MANUAL - UE on everyone except for Christina."
  },
  {
    unit1: ["christina", 5],
    unit2: ["tomo", 5],
    unit3: ["makoto", 5],
    unit4: ["muimi", 5],
    unit5: ["kaori", 5],
    damage: 4170626,
    boss: 4,
    clanBattle: 15,
    lap: 2,
    player: "Toon",
    notes: "FULL AUTO - UE on Makoto, Tomo, and Kaori."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 2536016,
    boss: 4,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Doesn't work, everybody dies."
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["anne", 4],
    unit3: ["yori", 5],
    unit4: ["anna", 5],
    unit5: ["illya", 5],
    damage: 3641203,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO - UE on both Anna and Yori."
  },
  {
    unit1: ["christina", 5],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["muimi", 5],
    unit5: ["kaori", 5],
    damage: 4893621,
    boss: 4,
    clanBattle: 15,
    lap: 2,
    player: "FennekZero",
    notes: "FULL AUTO - UE on Eriko, Makoto, and Kaori."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["rei", 5],
    unit3: ["djeeta", 5],
    unit4: ["makoto", 5],
    unit5: ["muimi", 5],
    damage: 2840880,
    boss: 3,
    clanBattle: 15,
    lap: 2,
    player: "FennekZero",
    notes: "SEMI-AUTO - UE on Shiori, Djeeta, Rei, and Makoto."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["tomo", 3],
    unit5: ["makoto", 5],
    damage: 3337258,
    boss: 1,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Shiori and Djeeta."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["tomo", 5],
    unit5: ["makoto", 5],
    damage: 3704519,
    boss: 1,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Shiori, Djeeta, and Tomo."
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["anne", 4],
    unit3: ["yori", 5],
    unit4: ["anna", 5],
    unit5: ["illya", 5],
    damage: 2407169,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - Nobody has UE on this team."
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["anne", 4],
    unit3: ["yori", 5],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 2953951,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Akari."
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["anne", 4],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 3275754,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes:
      "FULL AUTO - UE on Akari. Good if you are missing UE for both Yori and Anna, and you don't have Anne. If Illya dies, you can swap out Kyouka for Misato for a slightly safer run and a bit less damage."
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["misato", 5],
    unit3: ["anne", 4],
    unit4: ["akari", 5],
    unit5: ["illya", 5],
    damage: 2755480,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Akari and Misato."
  },
  {
    unit1: ["shinobu", 5],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["muimi", 5],
    unit5: ["kaori", 5],
    damage: 3396787,
    boss: 4,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Shinobu, Eriko, and Kaori."
  },
  {
    unit1: ["v shizuru", 3],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["muimi", 5],
    unit5: ["kaori", 5],
    damage: 3610303,
    boss: 4,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Eriko and Kaori."
  },
  {
    unit1: ["v shizuru", 3],
    unit2: ["rei", 5],
    unit3: ["tomo", 4],
    unit4: ["makoto", 5],
    unit5: ["muimi", 5],
    damage: 2847909,
    boss: 2,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Shinobu and Rei."
  },
  {
    unit1: ["v shizuru", 3],
    unit2: ["rei", 5],
    unit3: ["s tamaki", 5],
    unit4: ["tomo", 4],
    unit5: ["makoto", 5],
    damage: 2940705,
    boss: 2,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Rei."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["christina", 5],
    unit3: ["djeeta", 5],
    unit4: ["eriko", 5],
    unit5: ["makoto", 5],
    damage: 3600000,
    boss: 3,
    clanBattle: 15,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes: "MANUAL - UE on Shiori, Djeeta, and Eriko."
  },
  {
    unit1: ["christina", 5],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["muimi", 5],
    unit5: ["kaori", 5],
    damage: 4600000,
    boss: 4,
    clanBattle: 15,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes:
      "FULL AUTO - UE on Makoto, Eriko, and Kaori. If your Makoto is dying at 13-4, equipping her middle left gear will allow her to survive."
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["anne", 4],
    unit3: ["yori", 5],
    unit4: ["anna", 5],
    unit5: ["illya", 5],
    damage: 3600000,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes:
      "FULL AUTO - UE on Anna and Yori. If you are missing Anne or either of the requisite UEs, check the Boss 5 tab for replacement comps. "
  },
  {
    unit1: ["v shizuru", 3],
    unit2: ["rei", 5],
    unit3: ["s tamaki", 5],
    unit4: ["tomo", 4],
    unit5: ["makoto", 5],
    damage: 2800000,
    boss: 2,
    clanBattle: 15,
    lap: 2,
    player: "Symphonia",
    special: 1,
    notes:
      "FULL AUTO - UE on Rei and Makoto. Replace S Tamaki and others with flex DPS as needed."
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["misato", 5],
    unit3: ["anne", 4],
    unit4: ["anna", 5],
    unit5: ["illya", 5],
    damage: 3382335,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "realda",
    notes: "FULL AUTO - UE on Anna and Misato."
  },
  {
    unit1: ["kyouka", 5],
    unit2: ["s karyl", 5],
    unit3: ["misato", 5],
    unit4: ["anne", 4],
    unit5: ["illya", 5],
    damage: 2532153,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Misato."
  },
  {
    unit1: ["shinobu", 5],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["tomo", 5],
    unit5: ["muimi", 5],
    damage: 3542256,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "paoh",
    notes: "FULL AUTO - UE on Shinobu, Eriko, and Tomo."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["v shizuru", 3],
    unit3: ["djeeta", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 3900000,
    boss: 4,
    clanBattle: 15,
    lap: 2,
    player: "Symphonia",
    special: 2,
    notes: "FULL AUTO - UE on Shiori, Djeeta, Kaori, and Makoto. "
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["anne", 4],
    unit3: ["yori", 5],
    unit4: ["anna", 5],
    unit5: ["illya", 5],
    damage: 3600000,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "Symphonia",
    special: 2,
    notes:
      "FULL AUTO - UE on Anna and Yori. If you are missing Anne or either of the requisite UEs, check the Boss 5 tab for replacement comps. "
  },
  {
    unit1: ["shinobu", 5],
    unit2: ["christina", 5],
    unit3: ["eriko", 5],
    unit4: ["tomo", 5],
    unit5: ["muimi", 5],
    damage: 3400000,
    boss: 5,
    clanBattle: 15,
    lap: 2,
    player: "Symphonia",
    special: 2,
    notes: "FULL AUTO - UE on Shinobu, Eriko, and Tomo."
  },
  {
    unit1: ["shiori", 5],
    unit2: ["v shizuru", 3],
    unit3: ["djeeta", 5],
    unit4: ["makoto", 5],
    unit5: ["kaori", 5],
    damage: 3935014,
    boss: 4,
    clanBattle: 15,
    lap: 2,
    player: "Bshandon",
    notes: "FULL AUTO - UE on Shiori, Djeeta, Kaori, and Makoto. "
  },
  {
    unit1: ["shinobu", 5],
    unit2: ["djeeta", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 1900000,
    boss: 1,
    clanBattle: 15,
    lap: 3,
    player: "Symphonia",
    special: 3,
    notes:
      "FULL AUTO - UE on everyone, although Jun's doesn't matter as much. Can replace Shinobu with Rei (must have UE) for slightly less damage."
  },
  {
    unit1: ["yukari", 5],
    unit2: ["v shizuru", 3],
    unit3: ["christina", 5],
    unit4: ["makoto", 5],
    unit5: ["muimi", 5],
    damage: 2400000,
    boss: 2,
    clanBattle: 15,
    lap: 3,
    player: "Symphonia",
    special: 3,
    notes: "FULL AUTO - UE on Makoto."
  },
  {
    unit1: ["djeeta", 5],
    unit2: ["eriko", 5],
    unit3: ["makoto", 5],
    unit4: ["kaori", 5],
    unit5: ["jun", 5],
    damage: 2400000,
    boss: 3,
    clanBattle: 15,
    lap: 3,
    player: "Symphonia",
    special: 3,
    notes: "MANUAL - UE on everyone, although Jun's doesn't matter as much."
  },
  {
    unit1: ["rin", 5],
    unit2: ["v shizuru", 3],
    unit3: ["christina", 5],
    unit4: ["makoto", 5],
    unit5: ["muimi", 5],
    damage: 3000000,
    boss: 4,
    clanBattle: 15,
    lap: 3,
    player: "Symphonia",
    special: 3,
    notes:
      "ALMOST FULL AUTO - UE on Rin and Makoto. Spam click V Shizuru and Rin UB; turn off 2x speed when their UB is about to be up so you can UB as early as possible. It actually makes a difference, so don't skip this step."
  },
  {
    unit1: ["s karyl", 5],
    unit2: ["anne", 4],
    unit3: ["yori", 5],
    unit4: ["anna", 5],
    unit5: ["illya", 5],
    damage: 3600000,
    boss: 5,
    clanBattle: 15,
    lap: 3,
    player: "Symphonia",
    special: 3,
    notes:
      "FULL AUTO - UE on Anna and Yori. If you are missing Anne or either of the requisite UEs, check the Boss 5 tab for replacement comps. "
  }
  // {
  //   unit1: ["s saren", 3],
  //   unit2: ["djeeta", 5],
  //   unit3: ["eriko", 5],
  //   unit4: ["s makoto", 5],
  //   unit5: ["makoto", 5],
  //   damage: 4760000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["christina", 5],
  //   unit2: ["s makoto", 5],
  //   unit3: ["makoto", 5],
  //   unit4: ["muimi", 5],
  //   unit5: ["kaori", 5],
  //   damage: 4270000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["s kaori", 5],
  //   unit2: ["shinobu", 5],
  //   unit3: ["christina", 5],
  //   unit4: ["makoto", 5],
  //   unit5: ["muimi", 5],
  //   damage: 3320000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["s karyl", 5],
  //   unit2: ["neneka", 5],
  //   unit3: ["anne", 5],
  //   unit4: ["anna", 5],
  //   unit5: ["illya", 5],
  //   damage: 4500000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["h kyouka", 3],
  //   unit2: ["kyouka", 5],
  //   unit3: ["s karyl", 5],
  //   unit4: ["neneka", 5],
  //   unit5: ["akari", 5],
  //   damage: 4370000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["s karyl", 5],
  //   unit2: ["karyl", 5],
  //   unit3: ["nanaka", 5],
  //   unit4: ["neneka", 5],
  //   unit5: ["anne", 5],
  //   damage: 4409000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["h mimi", 3],
  //   unit2: ["christina", 5],
  //   unit3: ["djeeta", 5],
  //   unit4: ["s makoto", 5],
  //   unit5: ["makoto", 5],
  //   damage: 4670000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["s saren", 3],
  //   unit2: ["djeeta", 5],
  //   unit3: ["s makoto", 5],
  //   unit4: ["makoto", 5],
  //   unit5: ["muimi", 5],
  //   damage: 4468000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["h kyouka", 3],
  //   unit2: ["kyouka", 5],
  //   unit3: ["s karyl", 5],
  //   unit4: ["nanaka", 5],
  //   unit5: ["neneka", 5],
  //   damage: 4472000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // },
  // {
  //   unit1: ["christina", 5],
  //   unit2: ["djeeta", 5],
  //   unit3: ["eriko", 5],
  //   unit4: ["s makoto", 5],
  //   unit5: ["makoto", 5],
  //   damage: 5227000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "MOSTLY AUTO"
  // },
  // {
  //   unit1: ["s saren", 3],
  //   unit2: ["christina", 5],
  //   unit3: ["eriko", 5],
  //   unit4: ["s makoto", 5],
  //   unit5: ["makoto", 5],
  //   damage: 4718000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "MOSTLY AUTO"
  // },
  // {
  //   unit1: ["s saren", 3],
  //   unit2: ["christina", 5],
  //   unit3: ["djeeta", 5],
  //   unit4: ["s makoto", 5],
  //   unit5: ["makoto", 5],
  //   damage: 4681000,
  //   boss: 1,
  //   clanBattle: 21,
  //   lap: 3,
  //   player: "the sweatlords",
  //   notes: "FULL AUTO"
  // }
,
{unit1:["kokkoro",6],unit2:["christina",5],unit3:["rei",6],unit4:["hiyori",5],unit5:["makoto",5],damage:5131313,boss:5,clanBattle:25,lap:3,player:"paoh",notes:"FULL AUTO"}
,
{unit1:["yui",6],unit2:["s saren",3],unit3:["christina",5],unit4:["rei",6],unit5:["makoto",5],damage:5400852,boss:5,clanBattle:25,lap:3,player:"paoh",notes:"FULL AUTO"}
,
{unit1:["s saren",3],unit2:["v shizuru",3],unit3:["christina",5],unit4:["rei",6],unit5:["s makoto",5],damage:7641697,boss:2,clanBattle:25,lap:3,player:"paoh",notes:"FULL AUTO"}
,
{unit1:["ny suzume",1],unit2:["v shizuru",3],unit3:["christina",5],unit4:["rei",6],unit5:["s makoto",5],damage:5958562,boss:5,clanBattle:25,lap:3,player:"paoh",notes:"FULL AUTO"}
,
{unit1:["ny suzume",1],unit2:["v shizuru",3],unit3:["christina",5],unit4:["rei",6],unit5:["s makoto",5],damage:6000000,special:1,boss:5,clanBattle:25,lap:3,player:"paoh",notes:"FULL AUTO"}
,
{unit1:["s saren",3],unit2:["christina",5],unit3:["rei",6],unit4:["hiyori",5],unit5:["makoto",5],damage:5800053,boss:2,clanBattle:25,lap:3,player:"paoh",notes:"FULL AUTO"}
];